version: '3.8'
services:
  php:
    container_name: attribute_article
    image: alaugks/apache-php:8.2.12-v1.0-xdebug
    volumes:
      - ./app:/var/www/html
    environment:
      - XDEBUG_CONFIG=idekey=attribute_article
